module.exports = [
  "Draw a comic strip about {adjectiveSubjectPlace}",
  "Use your favorite building toy to build {subject}",
  "Write a story about {adjectiveSubjectPlace}",
  "Write a picture book about {adjectiveSubjectPlace}",
  "Make a puppet show about {adjectiveSubjectPlace}",
  "Invent a board game about {adjectiveSubjectPlace}",
  "Write a play about {adjectiveSubjectPlace}",
  "Design a video game about {adjectiveSubjectPlace}",
  "Write a song about {adjectiveSubjectPlace}",
  "Use found items to make {singularSubject}",
  "Make up a dance about {adjectiveSubjectPlace}",
  "Dress up and pretend you are {place}",
  "Dress up and pretend you are with {subject}",
  "Dress up and pretend you are with {subject} {place}",
  "Draw a maze that features {adjectiveSubjectPlace}",
  "Draw a map to find {adjectiveSubjectPlace}",
  "Make a crossword puzzle about {subject}",
  "Make a scrambled word puzzle about {subject}",
  "Make a word search puzzle about {subject}",
  "Make a quiz about {subject}",
  "Make a quiz with the theme: {place}",
  "Design an obstacle course with the theme: {subject}",
  "Design an obstacle course with the theme: {place}",
  "Draw a picture of {adjectiveSubjectPlace}",
  "Draw a picture of yourself with {adjectiveSubjectPlace}",
  "Draw a picture of yourself looking {adjective}",
  "Draw a picture of yourself {place}",
  "Draw a picture of someone you know with {adjectiveSubjectPlace}",
  "Draw a picture of someone you know looking {adjective}",
  "Draw a picture of someone you know {place}",
  "Read a book and then {bookActivity}",
  "Invent a new {gameType} game with the theme: {subject}",
  "Invent a new {gameType} game with the theme: {place}",
  "Invent a new game about {subject} using {gameElement}",
  "Make the menu for a restaurant with the theme: {adjectiveSubjectPlace}",
  "Make a mask that makes you look {adjective}",
  "Make a mask that makes you look like {singularSubject}",
  "Write a mad-libs story about {adjectiveSubjectPlace}",
  "Write a poem about {adjectiveSubjectPlace}",
  "Write a letter home, pretending you are {place}",
  "Make a bookmark that has {adjectiveSubjectPlace} on it",
  "Make a card for someone you know that features {adjectiveSubjectPlace}",
  "Make a paper airplane with {subject} on it",
  "Design a t-shirt with {subject} on it",
  "Design a poster for a movie about {adjectiveSubjectPlace}",
  "Design an outfit to wear {place}",
  "Design an outfit to wear when you are {adjective}",
  "Design a dream house for {adjectiveSubjectPlace}"
];
