module.exports = [
  "on a bridge",
  "under a bridge",
  "at the circus",
  "in the city",
  "at the zoo",
  "in outer space",
  "at the hospital",
  "at school",
  "at the beach",
  "at the park",
  "on a roller coaster",
  "on the moon",
  "in a factory",
  "underground",
  "in the garden",
  "on a farm",
  "at a wedding",
  "at a restaurant",
  "on a mountain",
  "on a boat",
  "at camp",
  "in the forest",
  "at home"  
];
